core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('theme_material_kit.urls'))
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from home import views
from home.views import ContactView, success, LocationView

urlpatterns = [
    path('', views.index, name='index'),
    path('bookpackage/', views.bookpackage, name='bookpackage'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('about/', views.about, name='about'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='pages/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='pages/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('deals/', views.offers, name="offers"),
    path('contact-us/', ContactView.as_view(), name='contact_us'),
    path('success/', success, name='success'),
    path('location/', LocationView.as_view(), name='location'),
    path('confirmbooking/', views.bookingview, name="confirmbooking")
]

home/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tier(models.Model):
    name = models.CharField(max_length=30, default="Gold")

    def __str__(self):
        return self.name


class Package(models.Model):
    PACKAGE_STATUS = (
        ("1", "Available"),
        ("2", "Not Available"),
    )

    PACKAGE_TYPE = (
        ("S", "Season"),
        ("M", "Monthly"),
        ("D", "Daily"),
    )
    tier = models.ForeignKey(Tier, on_delete=models.CASCADE)
    package_type = models.CharField(max_length=50, choices=PACKAGE_TYPE)
    price = models.IntegerField()
    capacity = models.IntegerField()
    status = models.CharField(choices=PACKAGE_STATUS, max_length=15)

    def __str__(self):
        return f'{self.package_type} {self.tier}'


class Reservation(models.Model):
    entry_date = models.DateField(auto_now=False)
    expiry_date = models.DateField()
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    guest = models.ForeignKey(User, on_delete=models.CASCADE)
    number_of_people = models.PositiveIntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])

    def __str__(self):
        return self.guest.username

class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.full_name

class Directions(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
<<<<<<< Updated upstream
        return self.title
=======
        return self.title


class Ride(models.Model):
    name = models.CharField(max_length=200)
    height_limit = models.PositiveIntegerField()
    capacity = models.PositiveIntegerField()
    is_available = models.BooleanField(default=True)
    duration = models.DurationField()

    def __str__(self):
        return self.name


class Users(models.Model):
    username = models.CharField(max_length=30, unique=True)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    pass1 = models.CharField(max_length=20)
    pass2 = models.CharField(max_length=20)

    def __str__(self):
        return self.username
>>>>>>> Stashed changes

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UsernameField, \
    PasswordResetForm, SetPasswordForm

from .models import User
from django.utils.translation import gettext_lazy as _

from django.forms import ModelForm
from .models import Reservation, Contact


class BookingForm(ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'


<<<<<<< Updated upstream
class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })
=======
# class RegistrationForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('username', 'email',)
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#
#         for field in self.fields:
#             self.fields[field].widget.attrs.update({'class': 'form-control',})
>>>>>>> Stashed changes


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "form-control"}),
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New Password"
    )
    new_password2 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm New Password"
    )


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Old Password'
    )

    new_password1 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New Password"
    )

    new_password2 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}), label="Confirm New Password"
    )

# class ContactForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     email = forms.EmailField()
#     message = forms.CharField(widget=forms.Textarea)

# class ContactForm(forms.Form):
#     name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}))
#     email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'xyz@gmail.com'}))
#     message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'placeholder': 'Describe your problem in at least 250 characters'}))

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'How can we help you?'}),
<<<<<<< Updated upstream
        }
=======
        }


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name','last_name','password')
>>>>>>> Stashed changes

home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View

from .forms import BookingForm
from .models import Tier, Reservation, Package, Contact, Directions
from theme_material_kit.forms import LoginForm, RegistrationForm, UserPasswordResetForm, UserSetPasswordForm, \
    UserPasswordChangeForm
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import ContactForm
from django.core.mail import send_mail
from django.views.generic import TemplateView
from django.conf import settings
from .forms import SignUpForm


# Create your views here.
@login_required(login_url='/login/')
def index(request):
    all_tier = Tier.objects.values_list('name', 'id').distinct().order_by()
    if request.method == 'POST':
        packages = Package.objects.all().filter(tier__id=int(request.POST['tier_id']))
        print(packages)
        data = {'packages': packages, 'all_tier': all_tier, 'flag': True}
        response = render(request, 'pages/index.html', data)
    else:
        response = render(request, 'pages/index.html', {'all_tier': all_tier})

    return HttpResponse(response)


@login_required(login_url='/login/')
def bookpackage(request):
    package_id = request.GET['package_id']
    package = Package.objects.all().filter(id=package_id)
    return HttpResponse(render(request, 'pages/bookpackage.html', {'package': package}))


class UserLoginView(auth_views.LoginView):
    template_name = 'pages/sign-in.html'
    form_class = LoginForm
    success_url = '/'


# def user_logout_view(request):
#     logout(request)
#     return redirect('/login/')

class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/login/')


# def registration(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             print('Account created successfully!')
#             return redirect('/login')
#         else:
#             print("Registration failed!")
#     else:
#         form = RegistrationForm()
#
#     context = {'form': form}
#     return render(request, 'pages/sign-up.html', context)

class RegistrationView(View):
    template_name = 'pages/sign-up.html'

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            print('Account created successfully!')
            return redirect('/login')
        else:
            print("Registration failed!")
        context = {'form': form}
        return render(request, self.template_name, context)

def about(request):
    return render(request, 'pages/about.html')


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'pages/password_reset.html'
    form_class = UserPasswordResetForm


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'pages/password_reset_confirm.html'
    form_class = UserSetPasswordForm


class UserPasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'pages/password_change.html'
    form_class = UserPasswordChangeForm


class ContactView(FormView):
    template_name = 'pages/contact_us.html'
    form_class = ContactForm
    success_url = reverse_lazy('success')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()

            # get the form data
            full_name = form.cleaned_data.get('full_name')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')

            # send email
            subject = 'New contact form submission'
            body = f'Full Name: {full_name}\nEmail: {email}\nMessage: {message}'
            sender_email = email
            recipient_list = ['adventure.quest.web@gmail.com']
            print("sending")
            send_mail(subject, body, sender_email, recipient_list)
            print("sent")

            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def success(request):
    return render(request, 'pages/success.html')

class LocationView(TemplateView):
    template_name = 'pages/location.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['GOOGLE_MAPS_API_KEY'] = settings.GOOGLE_MAPS_API_KEY
        return context

api_key = settings.GOOGLE_MAPS_API_KEY
url = f"https://maps.googleapis.com/maps/api/js?key={api_key}"


# Create your views here.
<<<<<<< Updated upstream
def booking_view(request):
    form = BookingForm()
    context = {'form': form}
    template_name = 'bookpackage.html'
    return render(request, template_name, context)
=======
@login_required(login_url='/login/')
def offers(request):
    offers_form = GroupPassForm()
    if request.method == 'POST':
        form = GroupPassForm(request.POST)
        if form.is_valid():
            print(1)
            group_pass = form.save(commit=False)
            group_pass.save()
            return render(request, 'pages/bookingsuccess.html')

        else:
            return HttpResponse("ERRORS" + str(form.errors))
            # print(form.errors)
    else:
        return render(request, 'pages/deals.html', {'form': offers_form})


def bookingview(request):
    if request.method == 'POST':
        try:
            print(request.POST)
            full_name = request.POST.get('full_name', False)
            total_person = int(request.POST.get('number_of_people', False))
            entry = request.POST.get('entry', False)
            package_id = request.POST.get('package_id', False)
            current_user = request.user
            user_object = User.objects.all().get(username=current_user)
            package_object = Package.objects.all().get(id=package_id)
            price_per_ticket = package_object.price
            total_price = total_person * price_per_ticket
            booking_id = str(package_id) + str(datetime.datetime.now())
            reservation = Reservation()

            reservation.full_name = full_name
            reservation.number_of_people = total_person
            reservation.entry_date = entry
            reservation.package = package_object
            reservation.user = user_object
            reservation.price_paid = total_price
            reservation.booking_id = booking_id

            reservation.save()
            return HttpResponse(
                render(request, 'pages/bookingconfirm.html', {'price': total_price, 'booking_id': booking_id}))
        except:
            return HttpResponse(render(request, 'pages/error.html'))
    else:
        return HttpResponse('Access Denied')

>>>>>>> Stashed changes

class LocationView(TemplateView):
    template_name = 'pages/location.html'

    def get_context_data(self, **kwargs):
        directions = Directions.objects.all()

        context = super().get_context_data(**kwargs)
        context['GOOGLE_MAPS_API_KEY'] = settings.GOOGLE_MAPS_API_KEY
        context['directions'] = directions
        return context

api_key = settings.GOOGLE_MAPS_API_KEY
url = f"https://maps.googleapis.com/maps/api/js?key={api_key}"


<<<<<<< Updated upstream
=======
def about(request):
    rides = Ride.objects.all()
    return render(request, 'pages/about.html', {'rides': rides})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'pages/sign-up.html', {'form': form})
>>>>>>> Stashed changes

home/templates/pages/bookingconfirm.html
{% extends 'pages/base_background.html' %}

{% block title %} Booking confirmed {% endblock title %}

{% block header %}


{% endblock header %}

{% block content %}

  <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Booking Confirmed</h4>
              </div>
            </div>
            <div class="card-body">
              Thank you! Your booking is confirmed and your total payment sum is {{ price }} $CAD and booking id is {{ booking_id }}. You can pay at the counter.
            </div>
            <div class="align-self-center my-4">
              <a href="/">
                      <button class="btn btn-success mb-0">
                        Return Home
                      </button>
               </a>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock content %}

  {% block footer %}

{#  {% include 'includes/footer_signin.html' %}#}

  {% endblock footer %}

home/templates/pages/bookingsuccess.html
{% extends 'pages/base_background.html' %}

{% block content %}
    {% csrf_token %}
  <div class="container my-5">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <h1 class="display-4 mb-3">Thank you!</h1>
        <p class="lead">We have confirmed your booking!</p>
        <a href="/" class="btn btn-primary mt-3">Back to Home</a>
      </div>
    </div>
  </div>
{% endblock %}

home/templates/pages/bookpackage.html
{% extends 'pages/base_background.html' %}
{% load static %}

{% block title %} WinPark {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

</div></div></div>

<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center">Confirm Booking</h3>
        <form role="form" id="contact-form" method="post" autocomplete="off" action="/confirmbooking/">
          {% csrf_token %}
          <div class="card-body">
            <div class="mb-4">
              <div class="input-group input-group-dynamic">
                <label class="form-label">Full Name</label>
                  <input class="form-control" id="full_name" name="full_name" aria-label="First Name..." type="text" required=True>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="input-group input-group-dynamic mb-4">
                  <label class="form-label">Number of people</label>
                <input type="number" id="number_of_people" name="number_of_people" class="form-control" required=True>
                </div>
              </div>
              <div class="col-md-6">
                <div class="input-group input-group-dynamic mb-4">
                    <label class="form-label">Date of Visit</label>
                    <input type="date" placeholder=" " min="2023-03-27" max="2025-04-30" id="entry" name="entry" class="form-control" required=True>
                </div>
              </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <p class="text-lg-start fw-bold">{{ package.tier.name}} {{ package.get_package_type_display }} Pass</p>
              </div>
                <div class="col-md-12">
                <p class="text-lg-start">Cost per ticket: <span class = "text-lg-start fw-bold">{{ package.price }}</span> $CAD</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-check form-switch mb-4 d-flex align-items-center">
                  <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" checked="true">
                  <label class="form-check-label ms-3 mb-0" for="flexSwitchCheckDefault">I agree to the <a href="javascript:;" class="text-dark"><u>Terms and Conditions</u></a>.</label>
                </div>
              </div>
              <div class="col-md-12">
                <button type="submit" class="btn btn-success w-100">Confirm</button>
                  <input type="hidden" name="package_id" value={{package.id}}>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content  %}

home/templates/pages/contact-us.html
{% extends 'pages/base_background.html' %}
{% load static %}

{% block body %} class="contact-us" {% endblock body %}

{% block content %}
  <!-- -------- START HEADER 8 w/ card over right bg image ------- -->
  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
            <div class="position-relative h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center" style="background-image: url('{% static 'img/illustrations/illustration-signin.jpg' %}'); background-size: cover;" loading="lazy"></div>
          </div>
          <div class="col-xl-5 col-lg-6 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-primary shadow-primary border-radius-lg p-3">
                  <h3 class="text-white text-primary mb-0">Contact us</h3>
                </div>
              </div>
              <div class="card-body">
                <p class="pb-3">
                  For further questions, including partnership opportunities, please email hello@creative-tim.com
                  or contact using our contact form.
                </p>
                <form id="contact-form" method="post" autocomplete="off">
                  <div class="card-body p-0 my-3">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="input-group input-group-static mb-4">
                          <label>Full Name</label>
                          <input type="email" class="form-control" placeholder="Full Name">
                        </div>
                      </div>
                      <div class="col-md-6 ps-md-2">
                        <div class="input-group input-group-static mb-4">
                          <label>Email</label>
                          <input type="email" class="form-control" placeholder="hello@creative-tim.com">
                        </div>
                      </div>
                    </div>
                    <div class="form-group mb-0 mt-md-0 mt-4">
                      <div class="input-group input-group-static mb-4">
                        <label>How can we help you?</label>
                        <textarea name="message" class="form-control" id="message" rows="6" placeholder="Describe your problem in at least 250 characters"></textarea>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12 text-center">
                        <button type="submit" class="btn bg-gradient-primary mt-3 mb-0">Send Message</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}

home/templates/pages/deals.html
{% extends 'pages/base_background.html' %}
{% load static %}

{% block title %} WinPark Deals {% endblock title %}

{% block body %} class="deals bg-gray-200" {% endblock body %}

{% block content %}
    <section>
    <div class="page-header min-vh-100" id="deals_header">
      <div class="container" >
        <div class="row">
          <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
             <div class="scrollable-div overflow-auto" style="color: white;">

                 <div  style="background-color: white; color: black; font-size: medium; opacity: 80%; text-align: justify; padding: 10px; font-weight: bold">
                     <h3>Adventure Quest - Group Pass</h3>
                      <ul style="list-style-type: none; font-size: medium">
                     <li style="font-weight: bold;">Family Pass <p style="font-weight: lighter">A family pass can be a fantastic way to enjoy a day of fun and excitement for a large group at a discounted price. With a family pass, up to 10 individuals can gain entry to the park using a single pass, which can be a great cost-saving option compared to purchasing individual tickets.
For enhanced experience, you can choose sub passes for family pass holders, which can further enhance the experience. These sub passes typically come in different tiers, such as gold, silver, and blue, and can provide access to additional rides, attractions, and amenities.</p></li>
                     <li>Student Pass <p style="font-weight: lighter">A student pass is a great way for students to save money while still enjoying all the fun and excitement an adventure park has to offer. With a student pass, students can get access to all the park's attractions at a reduced price.

The student pass comes with various sub pass options such as gold, silver, and blue, giving students the flexibility to choose a pass that best suits their needs and budget. Each sub pass offers different levels of access to the park's attractions, giving students the freedom to customize their experience.</p></li>
                     <li>Couple Pass <p style="font-weight: lighter">The couple pass is the perfect way for two people to enjoy the adventure park together while saving money. With the couple pass, both individuals can enjoy the park's attractions and activities at a discounted rate. This pass is ideal for couples who want to spend some quality time together while exploring the park.
With the couple pass, you and your partner can create unforgettable memories and have an amazing adventure together. Plus, with the money you save, you can even treat yourselves to some delicious food or souvenirs from the park. So why wait? Get your couple pass today and start your adventure!</p></li>
                 </ul>
                 </div>
             </div>
          </div>
          <div class="col-xl-5 col-lg-6 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-primary shadow-primary border-radius-lg p-3">
                  <h4 class="text-white text-primary mb-0">Welcome to Adventure Quest Offers</h4>
                </div>
              </div>
              <div class="card-body">
                <p class="pb-3">
                  Explore our offers on passes
                </p>
                   <form action="{% url 'offers' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                       <div style="text-align: center">
                           <input type="submit" value="Book Now!" class="btn bg-gradient-primary mt-3 mb-0" style="alignment: center">
                       </div>
                    </form>
                  <div style="text-align: center">
{#                      <input type="submit" value="Back to Home" class="btn bg-gradient-primary mt-3 mb-0" style="alignment: right" href="{% url home:index %}">#}
                      <a href="/" class="btn">Back to Home</a>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
    <script type="text/javascript">
            let cost;
            if (document.getElementById("id_sub_pass_type").value == 0) {
                cost = 9.99
            } else if (document.getElementById("id_sub_pass_type").value == 1) {
                cost = 14.99
            } else {
                cost = 19.99
            }
            document.getElementById("id_total_cost").value = document.getElementById("id_members").value * cost
            document.getElementById("id_sub_pass_type").onchange = total_package_cost;
            document.getElementById("id_members").onchange = total_package_cost;
            document.getElementById("id_pass_type").onchange = total_package_cost;



            const passTypeRadios = document.querySelectorAll('input[name="pass_type"]');

            // Add event listeners to each radio button
            for (let i = 0; i < passTypeRadios.length; i++) {
                passTypeRadios[i].addEventListener('change', function () {
                    // Call your function on change
                    coupleCheck();
                });
            }

            function coupleCheck() {
                if (document.getElementById("id_pass_type_2").checked) {
                    document.getElementById("id_members").value = 2
                } else {
                    document.getElementById("id_members").value = 1
                }

            }

            function total_package_cost() {
                total_number_of_passes();
                if (document.getElementById("id_sub_pass_type").value == 0) {
                    cost = 9.99
                } else if (document.getElementById("id_sub_pass_type").value == 1) {
                    cost = 14.99
                } else {
                    cost = 19.99
                }
                if (document.getElementById("id_pass_type_0").checked || document.getElementById("id_pass_type_1").checked) {

                    document.getElementById("id_total_cost").value = document.getElementById("id_members").value * cost
                } else {
                    document.getElementById("id_total_cost").value = cost * 2 * document.getElementById("id_number_of_pass").value
                }
            }

            function total_number_of_passes() {
                if (document.getElementById("id_pass_type_0").checked || document.getElementById("id_pass_type_1").checked) {
                    if (document.getElementById("id_members").value > 10) {
                        document.getElementById("id_number_of_pass").value = Math.ceil(document.getElementById("id_members").value / 10)
                    }else{
                        document.getElementById("id_number_of_pass").value = 1
                    }
                } else {
                    document.getElementById("id_number_of_pass").value = Math.ceil(document.getElementById("id_members").value / 2)
                }
            }
    </script>



{% endblock content %}